sources:
# Istio
- https://raw.githubusercontent.com/istio/istio/master/manifests/charts/base/files/crd-all.gen.yaml
# Gateway API
- https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/experimental-install.yaml
- https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml
# Prometheus Operator
- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
# Cert-Manager
- https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.crds.yaml
# Cilium
- https://raw.githubusercontent.com/cilium/cilium/master/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumnetworkpolicies.yaml
- https://raw.githubusercontent.com/cilium/cilium/master/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumclusterwidenetworkpolicies.yaml
- https://raw.githubusercontent.com/cilium/cilium/master/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumendpoints.yaml
- https://raw.githubusercontent.com/cilium/cilium/master/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumnodes.yaml
- https://raw.githubusercontent.com/cilium/cilium/master/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumidentities.yaml
- https://raw.githubusercontent.com/cilium/cilium/master/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumenvoyconfigs.yaml
- https://raw.githubusercontent.com/cilium/cilium/master/pkg/k8s/apis/cilium.io/client/crds/v2/ciliumlocalredirectpolicies.yaml
# NGINX Ingress Controller
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.9.6/deploy/static/provider/cloud/deploy.yaml
# Harbor
- https://raw.githubusercontent.com/goharbor/harbor-operator/main/manifests/cluster/deployment.yaml
# ArgoCD
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/application-crd.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/applicationset-crd.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/crds/appproject-crd.yaml
# FluxCD
- https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/crds/kustomize.toolkit.fluxcd.io_kustomizations.yaml
- https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/crds/source.toolkit.fluxcd.io_gitrepositories.yaml
- https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/crds/source.toolkit.fluxcd.io_helmrepositories.yaml
- https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/crds/source.toolkit.fluxcd.io_helmcharts.yaml
- https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/crds/helm.toolkit.fluxcd.io_helmreleases.yaml
# Kyverno
- https://raw.githubusercontent.com/kyverno/kyverno/main/config/crds/kyverno.io_clusterpolicies.yaml
- https://raw.githubusercontent.com/kyverno/kyverno/main/config/crds/kyverno.io_policies.yaml
- https://raw.githubusercontent.com/kyverno/kyverno/main/config/crds/kyverno.io_clustercleanuppolicies.yaml
- https://raw.githubusercontent.com/kyverno/kyverno/main/config/crds/kyverno.io_updaterequests.yaml
# KubeFlow
- https://raw.githubusercontent.com/kubeflow/kubeflow/master/components/common/crd-package/manifests.yaml
# Knative
- https://github.com/knative/serving/releases/download/knative-v1.14.0/serving-crds.yaml
- https://github.com/knative/eventing/releases/download/knative-v1.14.0/eventing-crds.yaml
# Crossplane
- https://raw.githubusercontent.com/crossplane/crossplane/master/cluster/crds/pkg.crossplane.io_providers.yaml
- https://raw.githubusercontent.com/crossplane/crossplane/master/cluster/crds/pkg.crossplane.io_configurations.yaml
- https://raw.githubusercontent.com/crossplane/crossplane/master/cluster/crds/apiextensions.crossplane.io_compositions.yaml
- https://raw.githubusercontent.com/crossplane/crossplane/master/cluster/crds/apiextensions.crossplane.io_compositionrevisions.yaml
- https://raw.githubusercontent.com/crossplane/crossplane/master/cluster/crds/apiextensions.crossplane.io_compositeresourcedefinitions.yaml
# Longhorn
- https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
# Tekton
- https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
# Kong
- https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/main/config/crd/bases/configuration.konghq.com_ingressclassparameters.yaml
- https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/main/config/crd/bases/configuration.konghq.com_kongconsumers.yaml
- https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/main/config/crd/bases/configuration.konghq.com_kongingresses.yaml
- https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/main/config/crd/bases/configuration.konghq.com_kongplugins.yaml
# OpenTelemetry Operator
- https://raw.githubusercontent.com/open-telemetry/opentelemetry-operator/main/config/crd/bases/opentelemetry.io_opentelemetrycollectors.yaml
- https://raw.githubusercontent.com/open-telemetry/opentelemetry-operator/main/config/crd/bases/opentelemetry.io_instrumentations.yaml
# Strimzi Kafka Operator
- https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/install/cluster-operator/043-Crd-kafka-strimzi-io-v1beta2.yaml
- https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/install/cluster-operator/044-Crd-kafkaconnect-strimzi-io-v1beta2.yaml
- https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/install/cluster-operator/045-Crd-kafkatopic-strimzi-io-v1beta2.yaml
- https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/install/cluster-operator/046-Crd-kafkauser-strimzi-io-v1beta2.yaml
- https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/install/cluster-operator/047-Crd-kafkabridge-strimzi-io-v1beta2.yaml
# Jaeger Operator
- https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/config/crd/bases/jaegertracing.io_jaegers.yaml
# Linkerd
- https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.14.9/pkg/charts/crds/resources/policy.linkerd.io_authorizationpolicies.yaml
- https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.14.9/pkg/charts/crds/resources/policy.linkerd.io_meshtls.yaml
- https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.14.9/pkg/charts/crds/resources/policy.linkerd.io_serverauthorizations.yaml
- https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.14.9/pkg/charts/crds/resources/policy.linkerd.io_servers.yaml
# Rook Ceph
- https://raw.githubusercontent.com/rook/rook/master/deploy/examples/crds.yaml
# Falco
- https://raw.githubusercontent.com/falcosecurity/falco/master/deployment/kubernetes/falco-crd.yaml
# KubeVirt
- https://raw.githubusercontent.com/kubevirt/kubevirt/main/manifests/release/kubevirt-cr.yaml
# Velero
- https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_backups.yaml
- https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_backupstoragelocations.yaml
- https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_deletebackuprequests.yaml
- https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_downloadrequests.yaml
- https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_podvolumebackups.yaml
- https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_podvolumerestores.yaml
- https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_restores.yaml
- https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_schedules.yaml
- https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_serverstatusrequests.yaml
- https://raw.githubusercontent.com/vmware-tanzu/velero/main/config/crd/v1/bases/velero.io_volumesnapshotlocations.yaml
# External DNS
- https://raw.githubusercontent.com/kubernetes-sigs/external-dns/master/docs/contributing/crd-source/crd-manifest.yaml
# Contour
- https://raw.githubusercontent.com/projectcontour/contour/main/examples/contour/01-crds.yaml
# Sealed Secrets
- https://raw.githubusercontent.com/bitnami-labs/sealed-secrets/main/helm/sealed-secrets/crds/sealedsecret-crd.yaml
# OpenEBS
- https://raw.githubusercontent.com/openebs/openebs/master/k8s/openebs-operator.yaml
# Cluster API
- https://raw.githubusercontent.com/kubernetes-sigs/cluster-api/main/config/crd/bases/cluster.x-k8s.io_clusters.yaml
- https://raw.githubusercontent.com/kubernetes-sigs/cluster-api/main/config/crd/bases/cluster.x-k8s.io_clusterclasses.yaml
- https://raw.githubusercontent.com/kubernetes-sigs/cluster-api/main/config/crd/bases/cluster.x-k8s.io_machinepools.yaml
- https://raw.githubusercontent.com/kubernetes-sigs/cluster-api/main/config/crd/bases/cluster.x-k8s.io_machinedeployments.yaml
- https://raw.githubusercontent.com/kubernetes-sigs/cluster-api/main/config/crd/bases/cluster.x-k8s.io_machines.yaml
- https://raw.githubusercontent.com/kubernetes-sigs/cluster-api/main/config/crd/bases/cluster.x-k8s.io_machinesets.yaml
# KEDA
- https://raw.githubusercontent.com/kedacore/keda/main/config/crd/bases/keda.sh_scaledjobs.yaml
- https://raw.githubusercontent.com/kedacore/keda/main/config/crd/bases/keda.sh_scaledobjects.yaml
- https://raw.githubusercontent.com/kedacore/keda/main/config/crd/bases/keda.sh_triggerauthentications.yaml
- https://raw.githubusercontent.com/kedacore/keda/main/config/crd/bases/keda.sh_clustertriggerauthentications.yaml
# Redis Operator
- https://raw.githubusercontent.com/spotahome/redis-operator/master/example/redisfailover-crd.yaml
# CockroachDB Operator
- https://raw.githubusercontent.com/cockroachdb/cockroach-operator/master/config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml
